export const boards = [
  {
    id: '1',
    name: 'Longboard 9\'0"',
    type: 'Longboard',
    description: 'Perfeita para iniciantes e ondas pequenas. Estabilidade e facilidade de remada.',
    price: 50,
    imageUrl: '/images/boards/Longboard.png',
  },
  {
    id: '2',
    name: 'Shortboard 6\'0"',
    type: 'Shortboard',
    description: 'Ideal para surfistas intermediários. Performance e manobrabilidade.',
    price: 45,
    imageUrl: '/images/boards/Shortboard.png',
  },
  {
    id: '3',
    name: 'Funboard 7\'2"',
    type: 'Funboard',
    description: 'Versátil e adaptável. Ótima para quem está evoluindo.',
    price: 48,
    imageUrl: '/images/boards/Funboard.png',
  },
  {
    id: '4',
    name: 'Fish Tail 5\'8"',
    type: 'Fish',
    description: 'Rápida e solta, excelente para manobras em ondas menores.',
    price: 40,
    imageUrl: '/images/boards/Fish Tail.png',
  },
  {
    id: '5',
    name: 'Soft Board 8\'0"',
    type: 'Softboard',
    description: 'Segura e fácil de usar, ideal para primeiras remadas e aulas.',
    price: 35,
    imageUrl: '/images/boards/Soft Board.png',
  },
  {
    id: '6',
    name: 'Big Wave Gun 10\'0"',
    type: 'Gun',
    description: 'Projetada para ondas grandes e potentes. Estabilidade e segurança no drop.',
    price: 70,
    imageUrl: '/images/boards/Big Wave Gun.png',
  },
  {
    id: '7',
    name: 'SUP Board 10\'6"',
    type: 'SUP',
    description: 'Ótima para passeios em águas calmas e pequenas ondas.',
    price: 60,
    imageUrl: '/images/boards/SUP Board.png',
  },
]

export const schools = [
  {
    id: '1',
    name: 'Escola de Surf Praia',
    description: 'Aulas para todos os níveis, desde iniciantes até avançados.',
    rating: 4.9,
    price: 120,
    imageUrl: '/images/schools/Surf School.png',
    languages: ['Português', 'Inglês'],
  },
  {
    id: '2',
    name: 'Instrutora Ana',
    description: 'Foco em técnicas de remada e posicionamento na prancha.',
    rating: 4.8,
    price: 110,
    imageUrl: '/images/schools/Surf Coach F.png',
    languages: ['Português'],
  },
  {
    id: '3',
    name: 'Instrutor Carlos',
    description: 'Especialista em surf de alta performance e manobras avançadas.',
    rating: 4.7,
    price: 130,
    imageUrl: '/images/schools/Surf Coach M.png',
    languages: ['Português', 'Espanhol'],
  },
] 